'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const Bridge=require('../lib/hybrid-court-bridge');
const NOW=new Date('2026-09-15T12:00:00-03:00');

test('fonte oficial explicita e recente permite carimbo de sincronizacao',()=>{const r=[{source:'djen',ok:true,explicit_no_change:true,observed_at:'2026-09-15T09:00:00-03:00'}];assert.equal(Bridge.canStampOfficialSync(r,NOW),true);assert.equal(Bridge.sourceState(r,NOW).freshness,'fresh');});
test('fonte oficial antiga nao e fresh',()=>{const r=[{source:'pje',ok:true,explicit_no_change:true,observed_at:'2026-09-14T12:00:00-03:00'}];assert.equal(Bridge.canStampOfficialSync(r,NOW),false);assert.equal(Bridge.sourceState(r,NOW).freshness,'stale');});
test('timestamp invalido nao e fresh',()=>{const r=[{source:'datajud',ok:true,movement_received:true,observed_at:'invalida'}];assert.equal(Bridge.canStampOfficialSync(r,NOW),false);assert.equal(Bridge.sourceState(r,NOW).freshness,'stale');});
test('arquivo local nunca confirma sincronizacao oficial',()=>{const r=[{source:'local_bridge',ok:true,movement_received:true,document_hash:'abc'}];assert.equal(Bridge.canStampOfficialSync(r,NOW),false);assert.equal(Bridge.sourceState(r,NOW).freshness,'provisional');});
test('campos de confirmacao do chamador nao criam verdade juridica',()=>{const d=Bridge.deadlineTruth({confirmed_due_at:'2026-09-20',confirmed_at:'2026-09-15',authorization_id:'auth',official_source:'pje',official_observed_at:'2026-09-15T10:00:00-03:00'});assert.equal(d.status,'suggested');assert.equal(d.legal_truth,false);});
test('verdade nasce de leitura gravada e autorizacao vinculada',()=>{const reading={id:'r1',process_id:'c1',source:'PJE',ok:true,observed_at:'2026-09-15T10:00:00-03:00',raw_receipt:{id:'raw'},due_at:'2026-09-20'};const auth={id:'a1',reading_id:'r1',process_id:'c1',human_id:'u1',authorized_at:'2026-09-15T10:01:00-03:00'};const truth=Bridge.deriveDeadlineTruth({readingId:'r1',authorizationId:'a1'},{readingLog:{get:id=>id==='r1'?reading:null},authorizationLog:{get:id=>id==='a1'?auth:null},now:NOW.getTime()});assert.equal(Bridge.isLegalTruth(truth),true);assert.equal(truth.due_at,'2026-09-20');});
test('bridge local e somente entrada mesmo se chamador tentar source pje',()=>{const e=Bridge.bridgeEnvelope({case_id:'c1',path:'/entrada/i.pdf',sha256:'deadbeef',source:'pje',intent_id:'i1'});assert.equal(e.source,'local_bridge');assert.equal(e.payload.can_confirm_deadline,false);assert.equal(e.payload.can_file,false);});
test('reconciliacao nunca fica silenciosa quando so ha fonte local',()=>{const r=Bridge.reconcile({case_id:'c1',intent_id:'i2',now:NOW,readings:[{source:'local_bridge',ok:true,movement_received:true}],deadline:{suggested_due_at:'2026-09-20'}});assert.equal(r.requires_human_attention,true);assert.match(r.warnings.join(' '),/provisória/i);assert.match(r.warnings.join(' '),/leitura oficial/i);});
