'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {authorizationForAction}=require('../lib/agent-capabilities');
const {verifyExecution}=require('../lib/verification-gate');
const {createExecutionReceipt,verifyReceipt}=require('../lib/execution-receipt');
const {createRuntimeFingerprint}=require('../lib/runtime-versioning');
const {executeNaturalOfficeCommand}=require('../lib/office-routes');

function processStore(initial){let rows=structuredClone(initial),version=1;return{async read(){return{processes:structuredClone(rows),version}},async mutate(fn){const draft=structuredClone(rows),value=fn(draft);rows=draft;version++;return{value:structuredClone(value),processes:structuredClone(rows),version}},snapshot(){return structuredClone(rows)}};}
function recordsStore(){const values=new Map();return{values,async list(){return[]},async change(key,fn){const next=await fn(values.get(key)||null);if(next!==undefined)values.set(key,structuredClone(next));return next}};}
function fakeEngine(){const submitted=[];return{submitted,async submit(input,actor){const task={id:'a'.repeat(32),...input,agente:'Redação',status:'na_fila',ator:actor};submitted.push(task);return task},async run(id){const task=submitted.find(x=>x.id===id);return{...task,status:'aguardando_revisao',processo_nome:'Caso Alfa',resultado:'MINUTA',sha256:'hash',runtime:{fingerprint:'runtime-1'}}},async list(){return submitted}};}

test('capabilities falham fechado e separam leitura, escrita e mensagem externa',()=>{assert.equal(authorizationForAction('reply_contact','secretaria').allowed,true);assert.equal(authorizationForAction('task','secretaria').allowed,false);assert.equal(authorizationForAction('acao_inexistente','admin').allowed,false);assert.equal(authorizationForAction('work_queue','admin').capability.effect,'read');});
test('verification gate não chama fila aceita de execução concluída',()=>{assert.equal(verifyExecution('task',{task_id:'t1',queue_status:'na_fila',deferred:true}).state,'accepted');assert.equal(verifyExecution('task',{task_id:'t1',result_status:'aguardando_revisao'}).state,'verified');assert.equal(verifyExecution('task',{task_id:'t1',result_status:'aguardando_dados'}).state,'blocked');});
test('mensagem externa só é verificada com provedor e histórico confirmados',()=>{assert.equal(verifyExecution('reply_contact',{provider_confirmed:true,history_recorded:false}).state,'unverified');assert.equal(verifyExecution('reply_contact',{provider_confirmed:true,history_recorded:true}).state,'verified');});
test('execution receipt é hashado e adulteração fica detectável',()=>{const receipt=createExecutionReceipt({action:'work_queue',resolved_action:'work_queue',actor:'admin',request:{text:'Veja o que precisa de mim'},result:{total:1},evidence:{observed:true}});assert.equal(receipt.verification.state,'verified');assert.equal(verifyReceipt(receipt),true);assert.equal(verifyReceipt({...receipt,result_hash:'0'.repeat(64)}),false);});
test('runtime fingerprint não guarda prompt bruto e muda quando o contexto muda',()=>{const a=createRuntimeFingerprint({policy_version:'p1',model_provider:'anthropic',model_name:'modelo',triage_prompt:'triagem secreta',system_prompt:'prompt juridico',playbook:'playbook',context:'caso A'});const b=createRuntimeFingerprint({policy_version:'p1',model_provider:'anthropic',model_name:'modelo',triage_prompt:'triagem secreta',system_prompt:'prompt juridico',playbook:'playbook',context:'caso B'});assert.notEqual(a.fingerprint,b.fingerprint);assert.equal(JSON.stringify(a).includes('triagem secreta'),false);assert.equal(JSON.stringify(a).includes('prompt juridico'),false);});
test('Core devolve recibo verificado quando envio e histórico foram observados',async()=>{const events=[],records=recordsStore();const deps={processStore:processStore([]),engine:fakeEngine(),records,receptionStore:{async list(){return[{numero:'5561999999999',nome:'Leidyanny',status:'aguardando_advogado'}]},async appendEvent(e){events.push(e)}},channelDelivery:async()=>true};const out=await executeNaturalOfficeCommand(deps,{text:'Responda a Leidyanny: Recebido.',profile:'admin',request_id:'msg-1'});assert.equal(out.receipt.verification.state,'verified');assert.equal(out.receipt.action,'reply_contact');assert.equal(out.receipt_persisted,true);assert.equal(events.length,1);assert.equal([...records.values.keys()].some(k=>k.startsWith('lex_execution_receipt_')),true);});
test('mande isso preserva a ação pedida no recibo e verifica pelo envio real',async()=>{const deps={processStore:processStore([]),engine:fakeEngine(),records:recordsStore(),receptionStore:{async list(){return[{numero:'5561999999999',nome:'Leidyanny',status:'aguardando_advogado'}]},async appendEvent(){}},channelDelivery:async()=>true};const out=await executeNaturalOfficeCommand(deps,{text:'Mande isso no WhatsApp para Leidyanny',previous_text:'Texto confirmado.',profile:'admin',request_id:'msg-2'});assert.equal(out.receipt.action,'send_previous');assert.equal(out.receipt.resolved_action,'reply_contact');assert.equal(out.receipt.verification.state,'verified');});
test('tarefa síncrona só fica verificada após observar aguardando revisão',async()=>{const numero='5001234-56.2026.8.13.0704';const deps={processStore:processStore([{id:'p1',nome:'Caso Alfa',numero,office_stage:'processos',status:'ATIVO'}]),engine:fakeEngine(),records:recordsStore()};const out=await executeNaturalOfficeCommand(deps,{text:'Faça a contestação do processo '+numero,profile:'admin',request_id:'task-1'});assert.equal(out.receipt.verification.state,'verified');assert.equal(out.receipt.runtime_fingerprint,'runtime-1');});
test('tarefa deferida fica aceita, nunca falsamente verificada',async()=>{const numero='5001234-56.2026.8.13.0704';const deps={processStore:processStore([{id:'p1',nome:'Caso Alfa',numero,office_stage:'processos',status:'ATIVO'}]),engine:fakeEngine(),records:recordsStore(),log:()=>{}};const out=await executeNaturalOfficeCommand(deps,{text:'Faça a contestação do processo '+numero,profile:'admin',request_id:'task-2',defer_task:true});assert.equal(out.receipt.verification.state,'accepted');assert.match(out.message,/aceita na fila/i);});
test('ambiguidade de processo gera recibo bloqueado e não cria tarefa',async()=>{const engine=fakeEngine();const deps={processStore:processStore([{id:'p1',nome:'Caso Alfa',cliente:'Cliente Igual'},{id:'p2',nome:'Caso Beta',cliente:'Cliente Igual'}]),engine,records:recordsStore()};const out=await executeNaturalOfficeCommand(deps,{text:'Faça a contestação do Cliente Igual',profile:'admin',request_id:'task-3'});assert.equal(out.receipt.verification.state,'blocked');assert.equal(engine.submitted.length,0);});
