document.write('<script src="office-ui-base.js"><\/script>');
(function(){
  function esc(v){const s=String(v??'');if(typeof window.lexEscape==='function')return window.lexEscape(s);return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
  function setPageTitle(text){const el=document.querySelector('.page-title');if(el)el.textContent=text;}
  function activate(btn){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');const sidebar=document.getElementById('sidebar'),overlay=document.getElementById('overlay');if(window.innerWidth<=900){sidebar?.classList.remove('open');overlay?.classList.remove('show');}}
  function openWhatsapp(btn){activate(btn||document.getElementById('lex-nav-whatsapp'));setPageTitle('WhatsApp do escritório');renderWhatsappCanal();}
  function renderWhatsappCanal(){if(typeof podeConfig==='function'&&!podeConfig()){document.getElementById('content').innerHTML='<div class="work-home"><p>Acesso restrito ao administrador.</p></div>';return;}document.getElementById('content').innerHTML=`<section class="work-home lex-canal"><div class="work-title"><div><div class="work-eyebrow">Canal dos clientes</div><h1>WhatsApp do escritório</h1><p>O cliente fala com o LEX Jurídico. O LEX organiza a conversa e chama o responsável quando uma decisão humana é necessária.</p></div><button class="btn-outline" onclick="typeof lexOpenReception==='function'?lexOpenReception(document.getElementById('lex-nav-recepcao')):ir('mensagens',null)">Ver fila</button></div><section class="work-command"><h2>Fluxo do atendimento</h2><ol class="lex-canal-steps"><li>O cliente fala com o LEX.</li><li>O LEX recebe, organiza e resolve apenas recepção e coleta.</li><li>Assunto jurídico sensível, estratégia, acordo, valor ou promessa fica aguardando autorização humana.</li><li>A resposta autorizada volta exatamente ao contato correto.</li></ol><div class="lex-canal-rule"><strong>Regra do escritório</strong><p>A máquina avisa e prepara. A pessoa responsável decide.</p></div><div class="work-links"><button class="btn-primary" onclick="typeof lexOpenReception==='function'?lexOpenReception(document.getElementById('lex-nav-recepcao')):ir('mensagens',null)">Abrir recepção</button><button class="btn-outline" onclick="ir('telegram',null)">Ir ao Telegram</button></div></section></section>`;}
  function renderTelegramCommercial(){if(typeof podeConfig==='function'&&!podeConfig()){document.getElementById('content').innerHTML='<div class="work-home"><p>Acesso restrito ao administrador.</p></div>';return;}const cfg=typeof getTgConfig==='function'?getTgConfig():{},token=esc(cfg.token||''),chatId=esc(cfg.chatId||'');document.getElementById('content').innerHTML=`<section class="work-home lex-canal"><div class="work-title"><div><div class="work-eyebrow">Canal complementar</div><h1>Telegram do escritório</h1><p>Segunda porta externa do mesmo LEX, mantendo cada contato em seu próprio fio.</p></div><button class="btn-outline" onclick="window.lexOpenWhatsapp()">Ver WhatsApp</button></div><details class="lex-canal-advanced work-command" open><summary>Telegram</summary><label class="fl" for="tg-token">Token do bot</label><input class="fi" id="tg-token" value="${token}"><label class="fl" for="tg-chatid">Chat ID</label><input class="fi" id="tg-chatid" value="${chatId}"><label class="fl" for="tg-modo">Modo</label><select class="fs" id="tg-modo"><option value="alertas" ${cfg.modo==='alertas'?'selected':''}>Alertas de prazo</option><option value="completo" ${cfg.modo==='completo'?'selected':''}>Chat do LEX</option></select><div class="work-links"><button class="btn-primary" onclick="salvarTgConfig()">Salvar</button><button class="btn-outline" onclick="testarTelegram()">Testar</button></div><div id="tg-status"></div></details></section>`;}
  function patchChannels(){window.renderWhatsappCanal=renderWhatsappCanal;window.lexOpenWhatsapp=()=>openWhatsapp(document.getElementById('lex-nav-whatsapp'));window.renderTelegram=renderTelegramCommercial;const nav=document.querySelector('#sidebar nav');if(nav){const tg=[...nav.querySelectorAll('.nav-btn')].find(b=>/Telegram/i.test(b.textContent||''));if(tg){tg.innerHTML='<span class="nav-icon">✈️</span> Telegram';tg.onclick=()=>{activate(tg);setPageTitle('Telegram');renderTelegramCommercial();};if(!document.getElementById('lex-nav-whatsapp')){const section=document.createElement('div');section.className='nav-section lex-canais-label';section.textContent='Canais';const btn=document.createElement('button');btn.id='lex-nav-whatsapp';btn.className='nav-btn';btn.innerHTML='<span class="nav-icon">📱</span> WhatsApp';btn.onclick=()=>openWhatsapp(btn);tg.before(section);section.after(btn);}}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchChannels);else patchChannels();
})();
document.write('<link rel="stylesheet" href="office-ui-v2.css">');
document.write('<link rel="stylesheet" href="lex-bank-ui.css">');
document.write('<link rel="stylesheet" href="office-ui-device.css">');
document.write('<link rel="stylesheet" href="login-theme.css">');
document.write('<link rel="stylesheet" href="office-flow-ui.css">');
document.write('<link rel="stylesheet" href="office-dossier-ui.css">');
document.write('<script src="office-ui-device.js"><\/script>');
document.write('<script src="office-ui-v2.js"><\/script>');
document.write('<script src="login-theme.js"><\/script>');
document.write('<script src="office-flow-ui.js"><\/script>');
document.write('<script src="lib/office-command.js"><\/script>');
document.write('<script src="office-command-ui.js"><\/script>');
document.write('<script src="reception-handoff-ui.js"><\/script>');
document.write('<script src="office-attachment-ui.js"><\/script>');
document.write('<script src="office-dossier-ui.js"><\/script>');
