document.write('<script src="lex-text.js"><\/script>');
document.write('<script src="office-ui-base.js"><\/script>');
(function(){
  function esc(v){const s=String(v??'');if(typeof window.lexEscape==='function')return window.lexEscape(s);return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
  function setPageTitle(text){const el=document.querySelector('.page-title');if(el)el.textContent=text;}
  function activate(btn){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active');const sidebar=document.getElementById('sidebar'),overlay=document.getElementById('overlay');if(window.innerWidth<=900){sidebar?.classList.remove('open');overlay?.classList.remove('show')}}
  function openWhatsapp(btn){activate(btn||document.getElementById('lex-nav-whatsapp'));setPageTitle('WhatsApp do escritório');renderWhatsappCanal()}
  function renderWhatsappCanal(){if(typeof podeConfig==='function'&&!podeConfig()){document.getElementById('content').innerHTML='<div class="work-home"><p>Acesso restrito ao administrador.</p></div>';return}const wa=typeof getWhatsappCfg==='function'?getWhatsappCfg():{};const numero=wa?.numero?String(wa.numero):'Configure o número do escritório';const assistente=typeof getNomeEscritorio==='function'&&getNomeEscritorio()!=='Sistema de Gestão'?getNomeEscritorio():'LEX';document.getElementById('content').innerHTML=`<section class="work-home lex-canal"><div class="work-title"><div><div class="work-eyebrow">Canal dos clientes</div><h1>WhatsApp do escritório</h1><p>O cliente fala com ${lexEscape(assistente)} por este número. O atendimento mantém cada conversa separada e chama o titular quando precisa de decisão.</p></div><button class="btn-outline" onclick="typeof lexOpenReception==='function'?lexOpenReception(document.getElementById('lex-nav-recepcao')):ir('mensagens',null)">Ver fila</button></div><div class="lex-canal-hero"><div class="lex-canal-phone"><span>Entrada dos clientes</span><strong>${lexEscape(numero)}</strong><p>WhatsApp configurado para este escritório.</p></div><div class="lex-canal-phone"><span>Mesa privada</span><strong>Canal privado do titular</strong><p>O LEX reporta nome, contato e assunto. O titular autoriza o que for sensível.</p></div></div><section class="work-command"><h2>Fluxo do atendimento</h2><ol class="lex-canal-steps"><li>O cliente manda mensagem no número configurado do escritório.</li><li>O LEX recebe, organiza e responde o que é apenas recepção.</li><li>Quando precisa de decisão, o LEX encaminha nome, contato e assunto ao canal privado do titular.</li><li>No canal privado, <code>Oi</code> ou <code>mesa</code> mostra quem está aguardando.</li><li>Para responder uma pessoa: <code>/responder NUMERO TEXTO EXATO</code>.</li></ol><div class="lex-canal-rule"><strong>Regra do escritório</strong><p>Processo, estratégia, acordo, honorário, promessa ou posição jurídica não saem sem autorização do titular.</p></div><div class="work-links"><button class="btn-primary" onclick="typeof lexOpenReception==='function'?lexOpenReception(document.getElementById('lex-nav-recepcao')):ir('mensagens',null)">Abrir recepção</button><button class="btn-outline" onclick="ir('telegram',null)">Ir ao Telegram</button></div></section></section>`}
  function renderTelegramCommercial(){if(typeof podeConfig==='function'&&!podeConfig()){document.getElementById('content').innerHTML='<div class="work-home"><p>Acesso restrito ao administrador.</p></div>';return}const cfg=typeof getTgConfig==='function'?getTgConfig():{},token=esc(cfg.token||''),chatId=esc(cfg.chatId||'');document.getElementById('content').innerHTML=`<section class="work-home lex-canal"><div class="work-title"><div><div class="work-eyebrow">Canal complementar</div><h1>Telegram do escritório</h1><p>Outra porta de atendimento do LEX. Cada pessoa permanece em seu fio e o responsável decide o que é sensível.</p></div><button class="btn-outline" onclick="window.lexOpenWhatsapp()">Ver WhatsApp</button></div><section class="work-command"><h2>Como usar</h2><ol class="lex-canal-steps"><li>O contato fala com o bot do escritório em conversa privada.</li><li><code>/resumo</code> abre a mesa do Telegram.</li><li><code>/respondertg ID TEXTO EXATO</code> envia só para aquele contato.</li></ol><div class="work-links"><button class="btn-primary" onclick="window.lexOpenWhatsapp()">Ver WhatsApp</button><button class="btn-outline" onclick="enviarResumoGeral()">Resumo geral</button></div></section><details class="lex-canal-advanced work-command"><summary>Ajustes avançados do Telegram</summary><label class="fl" for="tg-token">Token do bot já existente</label><input class="fi" id="tg-token" value="${token}"><label class="fl" for="tg-chatid">Seu Chat ID</label><input class="fi" id="tg-chatid" value="${chatId}"><label class="fl" for="tg-modo">Modo</label><select class="fs" id="tg-modo"><option value="alertas" ${cfg.modo==='alertas'?'selected':''}>Alertas de prazo</option><option value="completo" ${cfg.modo==='completo'?'selected':''}>Chat do assessor</option></select><div class="work-links"><button class="btn-primary" onclick="salvarTgConfig()">Salvar ajuste</button><button class="btn-outline" onclick="testarTelegram()">Testar alerta</button><button class="btn-outline" onclick="enviarAlertasPrazos()">Enviar prazos agora</button></div><div id="tg-status"></div><div id="tg-alerta-status"></div></details></section>`}
  function patchChannels(){document.body.classList.add('lex-commercial');window.renderWhatsappCanal=renderWhatsappCanal;window.lexOpenWhatsapp=()=>openWhatsapp(document.getElementById('lex-nav-whatsapp'));window.renderTelegram=renderTelegramCommercial;const nav=document.querySelector('#sidebar nav');if(nav){const tg=[...nav.querySelectorAll('.nav-btn')].find(b=>/Telegram/i.test(b.textContent||''));if(tg){tg.innerHTML='<span class="nav-icon">✈️</span> Telegram';tg.onclick=()=>{activate(tg);setPageTitle('Telegram');renderTelegramCommercial()};if(!document.getElementById('lex-nav-whatsapp')){const section=document.createElement('div');section.className='nav-section lex-canais-label';section.textContent='Canais';const btn=document.createElement('button');btn.id='lex-nav-whatsapp';btn.className='nav-btn';btn.innerHTML='<span class="nav-icon">📱</span> WhatsApp';btn.onclick=()=>openWhatsapp(btn);tg.before(section);section.after(btn)}}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',patchChannels);else patchChannels();
})();
document.write('<link rel="stylesheet" href="office-ui-v2.css">');
document.write('<link rel="stylesheet" href="lex-bank-ui.css">');
document.write('<link rel="stylesheet" href="office-ui-device.css">');
document.write('<link rel="stylesheet" href="login-theme.css">');
document.write('<link rel="stylesheet" href="office-flow-ui.css">');
document.write('<link rel="stylesheet" href="office-dossier-ui.css">');
document.write('<link rel="stylesheet" href="lex-polish.css">');
document.write('<script src="office-ui-device.js"><\/script>');
document.write('<script src="office-ui-v2.js"><\/script>');
document.write('<script src="login-theme.js"><\/script>');
document.write('<script src="office-flow-ui.js"><\/script>');
document.write('<script src="lib/office-command.js"><\/script>');
document.write('<script src="office-command-ui.js"><\/script>');
document.write('<script src="reception-handoff-ui.js"><\/script>');
document.write('<script src="office-attachment-ui.js"><\/script>');
document.write('<script src="office-dossier-ui.js"><\/script>');
document.write('<script src="lex2-interface-core.js"><\/script>');
document.write('<script src="lex2-coordinator-ui.js"><\/script>');
// Roteador único: carregado por último para prevalecer sobre as camadas antigas.
document.write('<script src="lex-nav.js"><\/script>');
