(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const procs=()=>{try{return typeof getProcs==='function'?(getProcs()||[]):[]}catch{return[]}};
const prep=()=>{try{return typeof getPrep==='function'?(getPrep()||[]):[]}catch{return[]}};
const first=()=>{try{return String(typeof getResponsavel==='function'?getResponsavel():'Kleuber').replace(/^dr\.?\s*/i,'').trim().split(/\s+/)[0]||'Kleuber'}catch{return'Kleuber'}};
const go=p=>{if(typeof ir==='function')ir(p,null)};
const openProc=id=>{if(typeof abrirProc==='function')abrirProc(id)};
const days=p=>{const raw=p?.prazoReal||p?.prazo||p?.dataPrazo;if(!raw)return 9999;let d;if(/^\d{2}\/\d{2}\/\d{4}$/.test(raw)){const [a,b,c]=raw.split('/');d=new Date(+c,+b-1,+a)}else d=new Date(raw);if(Number.isNaN(d.getTime()))return 9999;const n=new Date();n.setHours(0,0,0,0);d.setHours(0,0,0,0);return Math.round((d-n)/86400000)};
const active=p=>!/CONCLU|ARQUIV|ENTREGUE|GANHO|PERDIDO/i.test(String(p.status||''));
let procTab='todos',procQuery='',prazoTab='hoje';
function bot(size='lg'){return '<div class="lex-bot '+size+'"><span class="ant"></span><div class="head"><i></i><i></i><b>LEX</b></div></div>'}
function applyTheme(day){document.body.classList.toggle('lex-day',!!day);document.body.classList.toggle('dia',!!day);document.body.classList.toggle('noite',!day);localStorage.setItem('lex_commercial_theme',day?'day':'night');localStorage.setItem('lex_tema',day?'dia':'noite');const btn=document.getElementById('tema-btn');if(btn)btn.textContent=day?'🌙 Noite':'☀️ Dia'}
function themeInit(){const modern=localStorage.getItem('lex_commercial_theme'),legacy=localStorage.getItem('lex_tema');const day=modern?modern==='day':legacy?legacy==='dia':document.body.classList.contains('dia');applyTheme(day)}
window.lexToggleTheme=function(){applyTheme(!document.body.classList.contains('lex-day'))};
function installCommercialOverrides(){
  window.alternarTema=window.lexToggleTheme;
  window.varreduraInicial=function(){window._varreduraPendencias=[];document.getElementById('varredura-overlay')?.remove()};
  const oldSweep=document.getElementById('varredura-overlay');if(oldSweep)oldSweep.remove();
  if(!document.getElementById('lex-commercial-login-theme')){const st=document.createElement('style');st.id='lex-commercial-login-theme';st.textContent='body.lex-day #login-screen{background:#f4f7fb!important;color:#0b1d33!important}body.lex-day #login-screen>div>div:nth-child(2){background:#fff!important;border-color:#d9e4ef!important;box-shadow:0 20px 60px rgba(20,45,75,.10)!important}body.lex-day #login-screen input,body.lex-day #login-screen select{background:#f7fbff!important;border-color:#cfddea!important;color:#0b1d33!important}body.lex-day #login-screen label,body.lex-day #login-screen div{color:#334760}body.lex-day #login-screen #btn-login{color:#fff!important}';document.head.appendChild(st)}
}
function dock(on){return '<nav class="lex-dock"><button '+(on==='home'?'class="on"':'')+' onclick="lexHome()"><b>⌂</b><span>Início</span></button><button '+(on==='processos'?'class="on"':'')+' onclick="lexProcessos()"><b>▣</b><span>Processos</span></button><button class="lex-main '+(on==='lex'?'on':'')+'" onclick="lexChat()"><b>◉</b><span>LEX</span></button><button '+(on==='prazos'?'class="on"':'')+' onclick="lexPrazos()"><b>◷</b><span>Prazos</span></button><button '+(on==='mais'?'class="on"':'')+' onclick="lexMais()"><b>☰</b><span>Mais</span></button></nav>'}
function shell(title,body,on){const host=$('#content');if(!host)return;document.body.classList.add('lex-commercial');host.innerHTML='<main class="lex-screen"><header class="lex-top"><div><strong>LEX</strong><small>ESCRITÓRIO VIRTUAL INTELIGENTE</small></div><div class="lex-top-actions"><button onclick="lexToggleTheme()" aria-label="Tema">◐</button><button onclick="typeof toggleSidebar===\'function\'&&toggleSidebar()">☰</button></div></header>'+body+dock(on)+'</main>';const t=$('#page-title');if(t)t.textContent=title}
function badge(d){if(d===9999)return '';if(d<0)return '<em class="late">Vencido</em>';if(d===0)return '<em class="urgent">Prazo hoje</em>';if(d<=2)return '<em class="urgent">'+d+' dias</em>';if(d<=7)return '<em class="soon">'+d+' dias</em>';return '<em class="ok">Em curso</em>'}
function procRows(list){return list.slice(0,30).map(p=>'<button class="lex-proc-row" onclick="lexOpenProc(\''+esc(String(p.id))+'\')"><span class="bar"></span><span><code>'+esc(p.numero||'sem número')+'</code><strong>'+esc(p.nome||p.partes||'Processo')+'</strong><small>'+esc(p.tribunal||p.area||p.assunto||'')+'</small><span class="chips">'+badge(days(p))+'</span></span><b>›</b></button>').join('')||'<div class="lex-empty">Nenhum processo encontrado.</div>'}
function filteredProcesses(){let list=procs();if(procTab==='ativos')list=list.filter(active);else if(procTab==='prazos')list=list.filter(p=>days(p)<=7);if(procQuery)list=list.filter(p=>[p.nome,p.numero,p.partes,p.assunto,p.area,p.tribunal,p.status].join(' ').toLowerCase().includes(procQuery));return list}
function deadlineItems(){return procs().map(p=>({p,d:days(p)})).filter(x=>x.d<9999).sort((a,b)=>a.d-b.d)}
function deadlineRows(list){return list.slice(0,30).map(x=>'<button onclick="lexOpenProc(\''+esc(String(x.p.id))+'\')"><i class="'+(x.d<=0?'red':x.d<=2?'amber':'blue')+'"></i><span><strong>'+esc(x.p.nome||x.p.numero||'Processo')+'</strong><small>'+esc(x.p.numero||x.p.tribunal||'')+'</small></span><em>'+(x.d<0?'vencido '+Math.abs(x.d)+'d':x.d===0?'hoje':x.d+'d')+'</em></button>').join('')||'<div class="lex-empty">Nenhum prazo cadastrado.</div>'}
window.lexOpenProc=id=>openProc(id);
async function home(){const p=procs(),act=p.filter(active),soon=p.filter(x=>days(x)<=7).length;let tasks=[],reception=0;try{const d=await lexApi('/api/trabalho');tasks=Array.isArray(d.tarefas)?d.tarefas:[]}catch{}try{const d=await lexApi('/api/escritorio/recepcao');const r=d.itens||d.contatos||d.recepcao||[];reception=Array.isArray(r)?r.filter(x=>x.status!=='arquivado').length:0}catch{}const urgent=p.map(x=>({p:x,d:days(x)})).filter(x=>x.d<=2).sort((a,b)=>a.d-b.d).slice(0,4);const body='<section class="lex-home-hero"><div class="lex-hello">'+bot()+'<div><h1>Olá, Dr. '+esc(first())+'!</h1><p>Seu escritório em ação. Resultados hoje.</p></div></div><button class="lex-talk" onclick="lexChat()"><span>⌕</span><b>Fale com o LEX...</b><i>🎙</i><i>↑</i></button><div class="lex-actions"><button onclick="goLex(\'peticao\')">📄<span>Nova peça</span></button><button onclick="lexProcessos()">⌕<span>Consultar</span></button><button onclick="lexPrazos()">📅<span>Prazos</span></button><button onclick="document.getElementById(\'pdf-upload-input\')?.click()">⇧<span>Enviar</span></button></div></section><section><div class="lex-section-title"><h2>Hoje no seu escritório</h2><button onclick="lexMais()">Ver tudo ›</button></div><div class="lex-kpis"><button onclick="lexProcessos()"><b>'+act.length+'</b><span>Processos</span></button><button onclick="lexPrazos()"><b>'+soon+'</b><span>Prazos</span></button><button onclick="lexTarefas()"><b>'+tasks.filter(t=>!['concluida','falhou'].includes(t.status)).length+'</b><span>Tarefas</span></button><button onclick="goLex(\'mensagens\')"><b>'+reception+'</b><span>Mensagens</span></button></div></section><section><div class="lex-section-title"><h2>Agir agora</h2><button onclick="lexPrazos()">Ver todos ›</button></div><div class="lex-now">'+(urgent.length?urgent.map(x=>'<button onclick="lexOpenProc(\''+esc(String(x.p.id))+'\')"><span>⚠</span><span><strong>'+esc(x.p.nome||x.p.numero||'Processo')+'</strong><small>'+esc(x.p.numero||x.p.assunto||'')+'</small></span><em>'+(x.d<=0?'Hoje':x.d+'d')+'</em></button>').join(''):'<div class="lex-empty">Nenhuma ação crítica para hoje.</div>')+'</div></section><section><div class="lex-section-title"><h2>Setores do Escritório</h2><button onclick="lexEscritorio()">Ver todos ›</button></div>'+officeGrid(tasks,p)+'</section>';shell('Início',body,'home')}
function officeGrid(tasks,p){const busy=rx=>tasks.some(t=>!['concluida','falhou'].includes(t.status)&&rx.test(String(t.agente||t.tipo||t.instrucao||'')));const rows=[['Recepção','LEX Recepção',0,'cyan',/atend|recep/i],['Cadastro','LEX Cadastro',prep().length,'purple',/cadast|secret/i],['Iniciais','LEX Peticionamento',p.filter(x=>/inicial/i.test(String(x.setor||''))).length,'violet',/inicial|redac/i],['Processos','LEX Jurídico',p.filter(active).length,'green',/jurid|anal/i],['Prazos','LEX Controladoria',p.filter(x=>days(x)<=7).length,'amber',/prazo|control/i],['Peças / Perícia','LEX Perícia',tasks.filter(x=>/petic|peric|recurso|contest/i.test(String(x.tipo||x.instrucao||''))).length,'rose',/peric|redac|pesq/i],['Revisão','LEX Revisão',tasks.filter(x=>x.status==='aguardando_revisao').length,'blue',/revis/i],['Concluídos','LEX Finalização',p.filter(x=>!active(x)).length,'slate',/final|entreg/i]];return '<div class="lex-office-grid">'+rows.map(r=>'<button class="tone-'+r[3]+'" onclick="lexEscritorio()"><span><strong>'+r[0]+'</strong><b>'+r[2]+'</b></span><small>'+r[1]+' <i class="'+(busy(r[4])?'busy':'')+'"></i></small></button>').join('')+'</div>'}
window.lexHome=home;
window.lexProcessos=function(){const all=procs();const body='<div class="lex-page-head"><div><small>Carteira jurídica</small><h1>Processos</h1></div><button onclick="goLex(\'autuacao\')">＋</button></div><div class="lex-search"><span>⌕</span><input id="lex-q" value="'+esc(procQuery)+'" placeholder="Buscar processo, cliente, assunto..." oninput="lexFilterProc(this.value)"></div><div class="lex-tabs"><button class="'+(procTab==='todos'?'on':'')+'" onclick="lexSetProcFilter(\'todos\')">Todos <b>'+all.length+'</b></button><button class="'+(procTab==='ativos'?'on':'')+'" onclick="lexSetProcFilter(\'ativos\')">Ativos <b>'+all.filter(active).length+'</b></button><button class="'+(procTab==='prazos'?'on':'')+'" onclick="lexSetProcFilter(\'prazos\')">Prazos <b>'+all.filter(x=>days(x)<=7).length+'</b></button></div><div id="lex-proc-list">'+procRows(filteredProcesses())+'</div>';shell('Processos',body,'processos')};
window.lexSetProcFilter=tab=>{procTab=['todos','ativos','prazos'].includes(tab)?tab:'todos';window.lexProcessos()};
window.lexFilterProc=q=>{procQuery=String(q||'').toLowerCase();const h=$('#lex-proc-list');if(h)h.innerHTML=procRows(filteredProcesses())};
window.lexPrazos=function(){const all=deadlineItems();const visible=prazoTab==='hoje'?all.filter(x=>x.d===0):prazoTab==='7dias'?all.filter(x=>x.d>=0&&x.d<=7):all;const body='<div class="lex-page-head"><div><small>Controladoria</small><h1>Prazos</h1></div><button onclick="goLex(\'calendario\')">▣</button></div><div class="lex-tabs"><button class="'+(prazoTab==='hoje'?'on':'')+'" onclick="lexSetPrazoTab(\'hoje\')">Hoje <b>'+all.filter(x=>x.d===0).length+'</b></button><button class="'+(prazoTab==='7dias'?'on':'')+'" onclick="lexSetPrazoTab(\'7dias\')">7 dias <b>'+all.filter(x=>x.d>=0&&x.d<=7).length+'</b></button><button class="'+(prazoTab==='todos'?'on':'')+'" onclick="lexSetPrazoTab(\'todos\')">Todos</button></div><div class="lex-timeline">'+deadlineRows(visible)+'</div><div class="lex-recommend"><b>💡 LEX recomenda</b><p>Priorize prazos de hoje e dos próximos 2 dias.</p><button onclick="lexChat()">Organizar com o LEX</button></div>';shell('Prazos',body,'prazos')};
window.lexSetPrazoTab=tab=>{prazoTab=['hoje','7dias','todos'].includes(tab)?tab:'hoje';window.lexPrazos()};
window.lexTarefas=async function(){let tasks=[];try{const d=await lexApi('/api/trabalho');tasks=Array.isArray(d.tarefas)?d.tarefas:[]}catch{}const body='<div class="lex-page-head"><div><small>Fila operacional</small><h1>Tarefas</h1></div><button onclick="lexHome()">⌂</button></div><div class="lex-panel"><h2>Trabalho do LEX</h2>'+(tasks.length?tasks.slice(0,80).map(t=>'<div class="lex-agent-row"><i class="'+(['na_fila','executando'].includes(t.status)?'busy':'')+'"></i><span><strong>'+esc(t.agente||t.tipo||'LEX')+'</strong><small>'+esc(t.processo_nome||t.instrucao||'Tarefa')+'</small></span><em>'+esc(t.status||'')+'</em></div>').join(''):'<div class="lex-empty">Nenhuma tarefa registrada.</div>')+'</div>';shell('Tarefas',body,'mais')};
window.lexEscritorio=async function(){let tasks=[];try{const d=await lexApi('/api/trabalho');tasks=d.tarefas||[]}catch{}const body='<div class="lex-page-head"><div><small>Fluxo completo</small><h1>Escritório</h1></div><button onclick="lexHome()">⌂</button></div><div class="lex-coord">'+bot('sm')+'<div><strong>LEX · Coordenador geral</strong><small>Recebe a ordem, distribui aos setores e devolve para sua revisão.</small></div></div>'+officeGrid(tasks,procs())+'<div class="lex-panel"><h2>Atividade dos agentes</h2>'+(tasks.slice(0,12).map(t=>'<div class="lex-agent-row"><i class="'+(['na_fila','executando'].includes(t.status)?'busy':'')+'"></i><span><strong>'+esc(t.agente||'LEX')+'</strong><small>'+esc(t.processo_nome||t.instrucao||t.tipo||'Tarefa')+'</small></span><em>'+esc(t.status||'')+'</em></div>').join('')||'<div class="lex-empty">Nenhuma tarefa em andamento.</div>')+'</div>';shell('Escritório',body,'mais')};
window.lexSelectChatProcess=function(id){try{sessionStorage.setItem('lex_chat_process_id',String(id||''))}catch{}};
window.lexChat=function(selectedId){const items=procs();let saved='';try{saved=String(selectedId||sessionStorage.getItem('lex_chat_process_id')||'')}catch{saved=String(selectedId||'')}if(saved&&!items.some(p=>String(p.id)===saved))saved='';const body='<div class="lex-chat-head">'+bot()+'<div><h1>Olá, Dr. '+esc(first())+'!</h1><p>Como posso ajudar hoje?</p></div></div><div class="lex-search lex-chat-context"><span>⚖</span><select id="lex-chat-process" onchange="lexSelectChatProcess(this.value)" style="width:100%;min-height:44px;background:transparent;border:0;color:inherit;outline:0"><option value="">Conversa geral — sem processo</option>'+items.slice(0,150).map(p=>'<option value="'+esc(String(p.id))+'" '+(String(p.id)===saved?'selected':'')+'>'+esc((p.numero||'sem número')+' · '+(p.nome||p.partes||'Processo'))+'</option>').join('')+'</select></div><div class="lex-chat-shortcuts"><button onclick="lexPrefill(\'Analise o processo selecionado e a última decisão.\')">⚖ Analisar processo</button><button onclick="lexPrefill(\'Prepare uma minuta de peça para minha revisão.\')">📄 Minuta de peça</button><button onclick="lexPrazos()">◷ Ver prazos</button><button onclick="lexPrefill(\'Analise os riscos e próximos passos deste caso.\')">♟ Analisar risco</button><button onclick="lexPrefill(\'Pesquise jurisprudência atual e relevante para este caso.\')">⌕ Jurisprudência</button><button onclick="lexEscritorio()">▦ Setores</button></div><div class="lex-conversation" id="lex-conversation"><div class="lex-msg bot">Sou o LEX. Posso analisar casos, organizar prazos e acionar os agentes certos. As entregas relevantes continuam sob sua revisão.</div></div><form class="lex-chatbar" onsubmit="lexSendChat(event)"><textarea id="lex-chat-input" rows="1" placeholder="Digite sua mensagem..."></textarea><button type="button" title="Falar com o LEX" onclick="lexStartVoice()">🎙</button><button type="submit">↑</button></form><div class="lex-suggestion"><b>💡 Sugestão do LEX</b><span>Quer que eu organize primeiro os casos com prazo crítico?</span><button onclick="lexPrazos()">Ver prazos</button></div>';shell('LEX',body,'lex');setTimeout(()=>$('#lex-chat-input')?.focus(),60)};
window.lexStartVoice=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const input=$('#lex-chat-input');if(!input)return;if(!SR){input.focus();input.placeholder='Ditado não disponível neste navegador — use o microfone do teclado.';return}const rec=new SR();rec.lang='pt-BR';rec.interimResults=false;rec.maxAlternatives=1;rec.onresult=e=>{const text=e.results?.[0]?.[0]?.transcript||'';input.value=(input.value?input.value+' ':'')+text;input.focus()};rec.onerror=()=>{input.placeholder='Não consegui ouvir. Tente novamente.'};rec.start()};
window.lexPrefill=t=>{const i=$('#lex-chat-input');if(i){i.value=t;i.focus()}};
window.lexSendChat=async function(e){e?.preventDefault();const input=$('#lex-chat-input'),box=$('#lex-conversation');const text=input?.value.trim();if(!text||!box)return;const selected=String($('#lex-chat-process')?.value||'');const process=procs().find(p=>String(p.id)===selected)||null;window.lexSelectChatProcess(selected);box.insertAdjacentHTML('beforeend','<div class="lex-msg me">'+esc(text)+'</div>');input.value='';box.insertAdjacentHTML('beforeend','<div class="lex-msg bot pending" id="lex-pending">LEX está analisando…</div>');box.scrollTop=box.scrollHeight;try{const payload={mensagem:text};if(process){payload.processo_id=process.id;payload.numero_processo=process.numero||null;payload.processo_nome=process.nome||process.partes||null;payload.setor=process.setor||null}const d=await lexApi('/api/vivo/conversar',{method:'POST',body:JSON.stringify(payload)});const ans=d?.resposta||d?.reply||d?.mensagem||d?.texto||d?.resultado||d?.content||'Recebi a ordem. Vou organizar isso dentro do fluxo do escritório.';$('#lex-pending')?.remove();box.insertAdjacentHTML('beforeend','<div class="lex-msg bot">'+esc(typeof ans==='string'?ans:JSON.stringify(ans))+'</div>')}catch(err){$('#lex-pending')?.remove();box.insertAdjacentHTML('beforeend','<div class="lex-msg bot error">Não consegui concluir a conversa agora: '+esc(err.message||'falha no servidor')+'.</div>')}box.scrollTop=box.scrollHeight};
window.lexLegacy=function(page,label){try{if(typeof ir==='function'){ir(page,null);setTimeout(()=>{const c=$('#content');if(c&&!c.textContent.trim())window.lexMais()},80);return}}catch{}alert((label||'Função')+' ainda não está disponível nesta instalação.')};
window.lexMais=function(){const body='<div class="lex-page-head"><div><small>Funções complementares</small><h1>Mais</h1></div><button onclick="lexToggleTheme()">◐</button></div><div class="lex-menu"><button onclick="lexLegacy(\'contatos\',\'Clientes\')">👥<span>Clientes / Contatos</span><b>›</b></button><button onclick="lexLegacy(\'calendario\',\'Agenda\')">📅<span>Agenda</span><b>›</b></button><button onclick="lexLegacy(\'documentos\',\'Documentos\')">📄<span>Documentos</span><b>›</b></button><button onclick="lexTarefas()">✓<span>Tarefas</span><b>›</b></button><button onclick="lexLegacy(\'estatisticas\',\'Relatórios e estatísticas\')">▥<span>Relatórios / Estatísticas</span><b>›</b></button><button onclick="lexEscritorio()">▦<span>Escritório / Setores</span><b>›</b></button><button onclick="lexLegacy(\'configuracoes\',\'Configurações\')">⚙<span>Configurações</span><b>›</b></button></div><h2 class="lex-channel-title">Canais de comunicação</h2><div class="lex-channels"><button onclick="lexLegacy(\'whatsapp\',\'WhatsApp\')">🟢<span>WhatsApp</span></button><button onclick="lexLegacy(\'telegram\',\'Telegram\')">🔵<span>Telegram</span></button><button onclick="lexLegacy(\'mensagens\',\'Mensagens\')">✉️<span>Mensagens</span></button><button onclick="lexLegacy(\'pje\',\'PJe\')">Pe<span>PJe</span></button></div>';shell('Mais',body,'mais')};
window.goLex=p=>go(p);
window.renderPainel=home;window.renderTrabalho=window.lexTarefas;window.renderProcessos=window.lexProcessos;window.renderPrazos=window.lexPrazos;window.lexFocusV2=window.lexChat;
function hook(){themeInit();installCommercialOverrides();if(typeof window.ir==='function'&&!window.ir.__commercial){const old=window.ir;window.ir=function(page,button){if(page==='painel'){home();return}if(page==='trabalho'){window.lexTarefas();return}if(page==='processos'){window.lexProcessos();return}if(page==='prazos'){window.lexPrazos();return}return old.apply(this,arguments)};window.ir.__commercial=true}setTimeout(()=>{const c=$('#content');if(c&&c.offsetParent!==null&&!$('.lex-screen',c))home()},120)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();