'use strict';

const crypto=require('node:crypto');
const {cnjDigits}=require('./pje-sync');
const {createReadingLogEntry}=require('./reading-log-schema');
const UF_BY_TR={'01':'ac','02':'al','03':'ap','04':'am','05':'ba','06':'ce','07':'dft','08':'es','09':'go','10':'ma','11':'mt','12':'ms','13':'mg','14':'pa','15':'pb','16':'pr','17':'pe','18':'pi','19':'rj','20':'rn','21':'rs','22':'ro','23':'rr','24':'sc','25':'se','26':'sp','27':'to'};
function aliasForCnj(value){const cnj=cnjDigits(value);if(!cnj)throw new Error('Informe o número CNJ completo.');const ramo=cnj[13],tribunal=cnj.slice(14,16);if(ramo==='8'){const uf=UF_BY_TR[tribunal];if(!uf)throw new Error('Tribunal estadual não mapeado no Datajud.');return uf==='dft'?'tjdft':'tj'+uf}if(ramo==='4')return'trf'+String(Number(tribunal));if(ramo==='5')return tribunal==='00'?'tst':'trt'+String(Number(tribunal));if(ramo==='6'){const uf=UF_BY_TR[tribunal];if(!uf)throw new Error('Tribunal eleitoral não mapeado no Datajud.');return uf==='dft'?'tre-df':'tre-'+uf}if(ramo==='7')return'stm';if(ramo==='9'){if(tribunal==='13')return'tjmmg';if(tribunal==='21')return'tjmrs';if(tribunal==='26')return'tjmsp';throw new Error('Tribunal militar estadual não mapeado no Datajud.')}if(ramo==='1')return'stf';if(ramo==='3')return'stj';if(ramo==='2')return'cnj';throw new Error('Ramo de justiça ainda não mapeado no Datajud.')}
function movementText(mov={}){const nome=String(mov.nome||mov.descricao||mov.movimentoNacional?.nome||'Movimentação').trim(),comps=Array.isArray(mov.complementosTabelados)?mov.complementosTabelados:[],detalhes=comps.map(c=>String(c?.descricao||c?.nome||c?.valor||'').trim()).filter(Boolean);return detalhes.length?nome+' — '+detalhes.join('; '):nome}
function movementDate(mov={}){return String(mov.dataHora||mov.data||mov.dataMovimento||'').trim()}
function movementsFromPayload(payload){const hit=payload?.hits?.hits?.[0]?._source,rows=Array.isArray(hit?.movimentos)?hit.movimentos:[];return rows.map(m=>({data:movementDate(m),texto:movementText(m)})).filter(x=>x.data&&x.texto)}
function headerValue(response,name){try{return response?.headers?.get?.(name)||''}catch{return''}}
async function responseBody(response){if(typeof response?.text==='function'){const raw=await response.text();return{raw,payload:JSON.parse(raw)}}const payload=await response.json();return{raw:JSON.stringify(payload),payload}}
async function queryByCnj(value,{apiKey=process.env.DATAJUD_API_KEY,fetchImpl=globalThis.fetch}={}){const cnj=cnjDigits(value);if(!cnj)throw new Error('Informe o número CNJ completo.');const key=String(apiKey||'').trim();if(!key)throw new Error('DATAJUD_API_KEY não configurada.');if(typeof fetchImpl!=='function')throw new Error('Cliente HTTP do Datajud indisponível.');const alias=aliasForCnj(cnj),endpoint='https://api-publica.datajud.cnj.jus.br/api_publica_'+alias+'/_search',requestId=crypto.randomUUID(),requestedAt=new Date().toISOString(),response=await fetchImpl(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':/^APIKey\s/i.test(key)?key:'APIKey '+key},body:JSON.stringify({size:1,query:{match:{numeroProcesso:cnj}}})}),respondedAt=new Date().toISOString();if(!response?.ok){const status=Number(response?.status)||502;throw Object.assign(new Error('Datajud respondeu HTTP '+status+'.'),{status})}const {raw,payload}=await responseBody(response),movimentos=movementsFromPayload(payload);return{cnj,alias,movimentos,_audit:{endpoint,request_id:requestId,requested_at:requestedAt,responded_at:respondedAt,status_code:Number(response.status)||200,content_type:headerValue(response,'content-type'),remote_request_id:headerValue(response,'x-request-id')||headerValue(response,'request-id'),raw_receipt:raw}}}
function mergeMovements(processo,movimentos){const antigos=Array.isArray(processo.andamentos)?processo.andamentos.slice():[];let novos=0,duplicados=0;for(const mov of movimentos){const txt='[DATAJUD] '+mov.texto;if(antigos.some(a=>String(a.data)===String(mov.data)&&String(a.txt)===txt)){duplicados++;continue}antigos.push({data:mov.data,txt,origem:'datajud',cnj:cnjDigits(processo.numero),importado_em:new Date().toISOString()});novos++}antigos.sort((a,b)=>String(b.data||'').localeCompare(String(a.data||'')));return{andamentos:antigos,novos,duplicados}}
async function syncProcess(processStore,processoId,opts={}){if(!processoId)throw new Error('Informe o processo para consultar o Datajud.');const state=await processStore.read(),matches=state.processes.filter(p=>String(p.id)===String(processoId));if(matches.length!==1)throw Object.assign(new Error('Processo selecionado não existe.'),{status:404});const current=matches[0],cnj=cnjDigits(current.numero);if(!cnj)throw new Error('O processo selecionado ainda não possui número CNJ completo.');const same=state.processes.filter(p=>cnjDigits(p.numero)===cnj);if(same.length!==1)throw new Error('CNJ duplicado no LEX; revise o cadastro antes de consultar o Datajud.');const result=await queryByCnj(cnj,opts);const saved=await processStore.mutate(processes=>{const i=processes.findIndex(p=>String(p.id)===String(processoId));if(i<0)throw new Error('Processo mudou durante a consulta. Atualize a tela.');if(cnjDigits(processes[i].numero)!==cnj)throw new Error('Número CNJ mudou durante a consulta.');const merged=mergeMovements(processes[i],result.movimentos),reading=createReadingLogEntry({processo:cnj,process_id:processoId,source:'datajud',observed_at:result._audit.responded_at,ok:true,status_code:result._audit.status_code,proveniencia:{conector:'lib/datajud',endpoint:result._audit.endpoint,request_id:result._audit.request_id,authenticated:true,timestamp_requisicao:result._audit.requested_at,timestamp_resposta:result._audit.responded_at},content_type:result._audit.content_type,metadata:{remote_request_id:result._audit.remote_request_id||null},raw_receipt:result._audit.raw_receipt,movimentos_encontrados:result.movimentos.length,ultimo_movimento:result.movimentos[0]||null,sincronizado:true,explicit_no_change:merged.novos===0,movement_received:merged.novos>0});const readings=Array.isArray(processes[i].court_readings)?processes[i].court_readings:[];processes[i]={...processes[i],andamentos:merged.andamentos,court_readings:[reading,...readings].slice(0,50),datajud_atualizado_em:reading.observed_at,last_court_sync_at:reading.observed_at,last_court_sync_source:'datajud',datajud_alias:result.alias};return{processo:processes[i],reading,novos:merged.novos,duplicados:merged.duplicados}},opts.actor||'LEX Datajud');return{ok:true,synced:true,explicit_no_change:saved.value.novos===0,movement_received:saved.value.novos>0,cnj,alias:result.alias,consultados:result.movimentos.length,novos:saved.value.novos,duplicados:saved.value.duplicados,reading:saved.value.reading,processo:saved.value.processo}}
async function syncRegistered(processStore,opts={}){const state=await processStore.read(),rows=state.processes.filter(p=>cnjDigits(p.numero)),results=[];for(const p of rows){try{results.push({processo_id:p.id,...await syncProcess(processStore,p.id,opts)})}catch(error){results.push({processo_id:p.id,ok:false,error:error.message})}}return{ok:results.every(r=>r.ok!==false),total:rows.length,resultados:results}}
module.exports={aliasForCnj,movementsFromPayload,queryByCnj,mergeMovements,syncProcess,syncRegistered};
