'use strict';
const crypto=require('node:crypto');
const flow=require('./workflow');
const {appendToCase}=require('./event-ledger');
const STALE_AFTER_HOURS=12;
function todaySP(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(now)}
function hoursSince(iso,now=new Date()){if(!iso)return null;const t=Date.parse(iso);return Number.isFinite(t)?(now.getTime()-t)/36e5:null}
function canReachCourt(session={}){return session.device==='desktop'&&session.pje_session==='confirmed'&&session.tj_reachable===true}
function freshnessOf(p,now=new Date()){const due=flow.date(p.prazoReal||p.prazo);const synced=p.last_court_sync_at||null;const age=hoursSince(synced,now);let freshness='unknown';if(age!=null&&age<=STALE_AFTER_HOURS)freshness='fresh';else if(synced)freshness='stale';const days=due?Math.round((Date.parse(due)-Date.parse(todaySP(now)))/86400000):null;const confirmed=Boolean(p.deadline_confirmed_at||p.prazo_confirmado_em);return Object.freeze({case_id:p.id||null,prazo:due,days_to_due:days,last_court_sync_at:synced,freshness,fatal_unconfirmed:!confirmed})}
function sessionBlockMessage(s={}){if(s.device==='mobile'&&!canReachCourt(s))return'LEX não atualizou prazo: sem acesso ao TJ neste dispositivo.';if(s.pje_session==='expired')return'LEX não atualizou prazo: sessão do PJe expirada.';if(s.pje_session==='absent'||s.tj_reachable===false)return'LEX não atualizou prazo: sem acesso ao TJ.';return null}
function watchlist(processes,now=new Date()){return(Array.isArray(processes)?processes:[]).filter(p=>!flow.CLOSED.has(String(p.status||'').toUpperCase())).map(p=>{const f=freshnessOf(p,now),last=Array.isArray(p.andamentos)&&p.andamentos[0]?p.andamentos[0]:null;return Object.freeze({...f,titulo:p.nome||p.numero||p.id,intimacao:last?{data:last.data,texto:last.txt||last.texto||''}:null,proxacao:p.proxacao||null,needs_human_deadline_check:f.freshness!=='fresh'||f.days_to_due==null||f.days_to_due<=5})}).sort((a,b)=>(a.days_to_due==null?9999:a.days_to_due)-(b.days_to_due==null?9999:b.days_to_due))}
async function openOfficeWatch({processes,session,intent_id,actor_id='LEX',syncFn,now=new Date()}){const intent=String(intent_id||crypto.randomUUID()),block=sessionBlockMessage(session),base={intent_id:intent,actor_type:'system',actor_id,event_type:'court_sync_attempted',payload:{device:session?.device||null,pje_session:session?.pje_session||null,tj_reachable:session?.tj_reachable===true}};if(block||typeof syncFn!=='function'||!canReachCourt(session)){const warning=block||'LEX não atualizou prazo: sem acesso ao TJ.';return Object.freeze({ok:false,intent_id:intent,synced:false,warning,items:watchlist(processes,now).map(i=>({...i,freshness:i.freshness==='fresh'?'stale':i.freshness,warning})),ledger_event:{...base,result:'blocked',payload:{...base.payload,warning}}})}const result=await syncFn({processes,session,intent_id:intent,now});const explicit=result?.ok===true&&(result?.explicit_no_change===true||result?.movement_received===true||result?.synced===true);const after=explicit?(result.processes||processes):processes;return Object.freeze({ok:explicit,intent_id:intent,synced:explicit,warning:explicit?null:(result?.warning||'LEX não atualizou prazo: falha no TJ.'),items:watchlist(after,now),ledger_event:{...base,result:explicit?'synced':'failed',causation_id:result?.causation_id||null}})}
function applySyncStamp(p,now=new Date()){return{...p,last_court_sync_at:now.toISOString(),atualizado_em:now.toISOString()}}
function recordWatch(current,event){const events=current?.case_events||[];if(event?.intent_id&&events.some(e=>e.intent_id===event.intent_id&&e.event_type===event.event_type))return current;return appendToCase(current,event)}
module.exports={STALE_AFTER_HOURS,canReachCourt,freshnessOf,sessionBlockMessage,watchlist,openOfficeWatch,applySyncStamp,recordWatch};
