'use strict';
const crypto=require('node:crypto');
const flow=require('./workflow');
const {appendToCase}=require('./event-ledger');
const Bridge=require('./hybrid-court-bridge');
const {isCourtSyncEvidence}=require('./court-sync-evidence');
const STALE_AFTER_HOURS=Bridge.STALE_AFTER_HOURS;
function todaySP(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(now)}
function canReachCourt(session={}){return session.device==='desktop'&&session.pje_session==='confirmed'&&session.tj_reachable===true}
function freshnessOf(p,now=new Date(),syncEvidence=null){const due=flow.date(p.prazoReal||p.prazo);const evidence=isCourtSyncEvidence(syncEvidence)&&(!syncEvidence.process_id||String(syncEvidence.process_id)===String(p.id))?syncEvidence:null;const synced=evidence?.observed_at||null;const source=evidence?.source?String(evidence.source).toLowerCase():null;const readings=evidence?[{source,ok:true,explicit_no_change:evidence.explicit_no_change===true,movement_received:evidence.movement_received===true,observed_at:synced}]:[];const freshness=Bridge.sourceState(readings,now).freshness;const days=due?Math.round((Date.parse(due)-Date.parse(todaySP(now)))/86400000):null;const authority=Bridge.deadlineTruth({suggested_due_at:due},now);return Object.freeze({case_id:p.id||null,prazo:due,days_to_due:days,last_court_sync_at:synced,freshness,fatal_unconfirmed:!authority.legal_truth,deadline_status:authority.status,deadline_legal_truth:authority.legal_truth})}
function sessionBlockMessage(s={}){if(s.device==='mobile'&&!canReachCourt(s))return'LEX não atualizou prazo: sem acesso ao TJ neste dispositivo.';if(s.pje_session==='expired')return'LEX não atualizou prazo: sessão do PJe expirada.';if(s.pje_session==='absent'||s.tj_reachable===false)return'LEX não atualizou prazo: sem acesso ao TJ.';return null}
function evidenceForProcess(evidences,p){return(Array.isArray(evidences)?evidences:[]).find(e=>isCourtSyncEvidence(e)&&(!e.process_id||String(e.process_id)===String(p.id)))||null}
function watchlist(processes,now=new Date(),syncEvidences=[]){return(Array.isArray(processes)?processes:[]).filter(p=>!flow.CLOSED.has(String(p.status||'').toUpperCase())).map(p=>{const f=freshnessOf(p,now,evidenceForProcess(syncEvidences,p)),last=Array.isArray(p.andamentos)&&p.andamentos[0]?p.andamentos[0]:null;return Object.freeze({...f,titulo:p.nome||p.numero||p.id,intimacao:last?{data:last.data,texto:last.txt||last.texto||''}:null,proxacao:p.proxacao||null,needs_human_deadline_check:f.freshness!=='fresh'||!f.deadline_legal_truth||f.days_to_due==null||f.days_to_due<=5})}).sort((a,b)=>(a.days_to_due==null?9999:a.days_to_due)-(b.days_to_due==null?9999:b.days_to_due))}
async function openOfficeWatch({processes,session,intent_id,actor_id='LEX',syncFn,now=new Date()}){const intent=String(intent_id||crypto.randomUUID()),block=sessionBlockMessage(session),base={intent_id:intent,actor_type:'system',actor_id,event_type:'court_sync_attempted',payload:{device:session?.device||null,pje_session:session?.pje_session||null,tj_reachable:session?.tj_reachable===true}};if(block||typeof syncFn!=='function'||!canReachCourt(session)){const warning=block||'LEX não atualizou prazo: sem acesso ao TJ.';return Object.freeze({ok:false,intent_id:intent,synced:false,warning,items:watchlist(processes,now).map(i=>({...i,warning})),ledger_event:{...base,result:'blocked',payload:{...base.payload,warning}}})}const result=await syncFn({processes,session,intent_id:intent,now});const evidences=(Array.isArray(result?.sync_evidences)?result.sync_evidences:[]).filter(isCourtSyncEvidence);const explicit=evidences.length>0;const after=explicit?(result.processes||processes):processes;const source=explicit?String(evidences[0].source).toLowerCase():null;const observedAt=explicit?evidences[0].observed_at:null;return Object.freeze({ok:explicit,intent_id:intent,synced:explicit,warning:explicit?null:(result?.warning||'LEX não atualizou prazo: fonte oficial sem evidência verificada.'),items:watchlist(after,now,evidences),ledger_event:{...base,result:explicit?'synced':'failed',causation_id:result?.causation_id||null,payload:{...base.payload,source,observed_at:observedAt,official_sync:explicit}}})}
function applySyncStamp(p,syncEvidence){if(!isCourtSyncEvidence(syncEvidence))return p;if(syncEvidence.process_id&&String(syncEvidence.process_id)!==String(p.id))return p;const observedAt=syncEvidence.observed_at;return{...p,last_court_sync_at:observedAt,last_court_sync_source:String(syncEvidence.source).toLowerCase(),atualizado_em:observedAt}}
function recordWatch(current,event){const events=current?.case_events||[];if(event?.intent_id&&events.some(e=>e.intent_id===event.intent_id&&e.event_type===event.event_type))return current;return appendToCase(current,event)}
module.exports={STALE_AFTER_HOURS,canReachCourt,freshnessOf,sessionBlockMessage,watchlist,openOfficeWatch,applySyncStamp,recordWatch};
