'use strict';
const crypto=require('node:crypto');
const {appendToCase}=require('./event-ledger');
const SOURCES=new Set(['whatsapp','telegram','datajud','pje','lex','manual','upload']);
const BAD=new Set(['blur','low_resolution','cropped','low_contrast','corrupt','wrong_orientation','unreadable']);
function sha256(v){return crypto.createHash('sha256').update(Buffer.isBuffer(v)?v:String(v||'')).digest('hex')}
function sourceOf(v){const s=String(v||'manual').toLowerCase();return SOURCES.has(s)?s:'manual'}
function issue(i={}){return Object.freeze({page_number:Number(i.page_number||i.page||1),region:i.region||null,issue_type:String(i.issue_type||i.type||'unreadable'),severity:String(i.severity||'warning'),message:String(i.message||'Documento precisa de conferência.')})}
function qualityCheck(input={}){const issues=(input.issues||[]).map(issue);const rejected=issues.some(x=>x.severity==='critical'||BAD.has(x.issue_type));return Object.freeze({overall_status:rejected?'rejected':issues.length?'warning':'passed',sharpness:input.sharpness??null,contrast:input.contrast??null,resolution:input.resolution??null,orientation:input.orientation??null,cropping:input.cropping??null,integrity:input.integrity??null,issues})}
function receive({case_id,document_id,source='manual',name,mime_type,bytes,sha256:knownHash,quality={},now=new Date()}={}){if(!case_id)throw new Error('Documento precisa estar vinculado a um processo.');const hash=knownHash||sha256(bytes||name||document_id);const q=qualityCheck(quality);const status=q.overall_status==='rejected'?'quarantined':'gate_passed';return Object.freeze({id:document_id||crypto.randomUUID(),case_id,source:sourceOf(source),original_name:String(name||'documento'),mime_type:String(mime_type||'application/octet-stream'),sha256:hash,received_at:now.toISOString(),status,quality:q,productive:q.overall_status!=='rejected'})}
function probableDuplicate(doc,documents=[]){return documents.find(d=>String(d.case_id)===String(doc.case_id)&&String(d.sha256)===String(doc.sha256)&&String(d.id)!==String(doc.id))||null}
function assertProductive(doc){if(!doc||doc.status==='quarantined'||doc.quality?.overall_status==='rejected'||doc.productive===false){const e=new Error('Documento em quarentena: não pode alimentar análise, peça ou perícia sem resolução auditada.');e.code='DOCUMENT_GATE_BLOCKED';throw e}return true}
function override(doc,{authorization_id,actor_id,reason,now=new Date()}={}){if(!authorization_id||!actor_id)throw new Error('Override exige autorização humana identificada.');return Object.freeze({...doc,status:'gate_override',productive:true,gate_override:{authorization_id,actor_id,reason:String(reason||'Uso consciente de documento com qualidade reduzida.'),at:now.toISOString()}})}
function record(current,doc,{intent_id,actor_id='LEX Documental'}={}){const existing=(current?.case_events||[]).some(e=>intent_id&&String(e.intent_id||'')===String(intent_id));if(existing)return current;let out=appendToCase(current,{event_type:'document.received',intent_id:intent_id||null,actor_type:'system',actor_id,document_id:doc.id,result:'received',payload:{source:doc.source,sha256:doc.sha256,name:doc.original_name}});out=appendToCase(out,{event_type:doc.status==='quarantined'?'document.quarantined':'document.gate_passed',intent_id:intent_id?String(intent_id)+':gate':null,actor_type:'system',actor_id,document_id:doc.id,result:doc.status,payload:{quality:doc.quality}});return out}
module.exports={SOURCES,sha256,qualityCheck,receive,probableDuplicate,assertProductive,override,record};
